config/routes.rb
Rails.application.routes.draw do
  resources :productds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/productd.rb
class Productd < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/productds_controller.rb
class ProductdsController < ApplicationController
  before_action :set_productd, only: %i[ show edit update destroy ]

  # GET /productds or /productds.json
  def index
    @productds = Productd.all
  end

  # GET /productds/1 or /productds/1.json
  def show
  end

  # GET /productds/new
  def new
    @productd = Productd.new
  end

  # GET /productds/1/edit
  def edit
  end

  # POST /productds or /productds.json
  def create
    @productd = Productd.new(productd_params)

    respond_to do |format|
      if @productd.save
        format.html { redirect_to productd_url(@productd), notice: "Productd was successfully created." }
        format.json { render :show, status: :created, location: @productd }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @productd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productds/1 or /productds/1.json
  def update
    respond_to do |format|
      if @productd.update(productd_params)
        format.html { redirect_to productd_url(@productd), notice: "Productd was successfully updated." }
        format.json { render :show, status: :ok, location: @productd }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @productd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productds/1 or /productds/1.json
  def destroy
    @productd.destroy

    respond_to do |format|
      format.html { redirect_to productds_url, notice: "Productd was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_productd
      @productd = Productd.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def productd_params
      params.require(:productd).permit(:name, :price, :vendor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productds_helper.rb
module ProductdsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductRegister</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/productds/_form.html.erb
<%= form_with(model: productd, local: true) do |form| %>
  <% if productd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(productd.errors.count, "error") %> prohibited this productd from being saved:</h2>

      <ul>
      <% productd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :vendor %>
    <%= form.text_field :vendor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/productds/edit.html.erb
<h1>Editing Productd</h1>

<%= render 'form', productd: @productd %>

<%= link_to 'Show', @productd %> |
<%= link_to 'Back', productds_path %>

app/views/productds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Vendor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productds.each do |productd| %>
      <tr>
        <td><%= productd.name %></td>
        <td><%= productd.price %></td>
        <td><%= productd.vendor %></td>
        <td><%= link_to 'Show', productd %></td>
        <td><%= link_to 'Edit', edit_productd_path(productd) %></td>
        <td><%= link_to 'Destroy', productd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Productd', new_productd_path %>

app/views/productds/new.html.erb
<h1>New Productd</h1>

<%= render 'form', productd: @productd %>

<%= link_to 'Back', productds_path %>

app/views/productds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @productd.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @productd.price %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @productd.vendor %>
</p>

<%= link_to 'Edit', edit_productd_path(@productd) %> |
<%= link_to 'Back', productds_path %>